#!/bin/bash
# made by: gobonja

select_language () {
LANG=`yad --window-icon=document-save --image=document-save --image-on-top --list --height=590 --width=300  \
	  --title="LibreOffice Installer" --text="Select language pack from the list below:" \
          --search-column=1 --separator= --print-column=2 --column="Language" --column="Code" \
"English US" en-US \
"English GB" en-GB \
"English ZA" en-ZA \
Afrikaans af \
Albanien sq \
Arabic ar \
"Assamese (India)" as \
Asturianu ast \
"Bahasa Indonesia" id \
Basque eu \
Belarusian be \
Bengali bn \
Bodo brx \
Bosnian bs \
Breton br \
Bulgarian bg \
Burmese my \
"Catalan (Valencia)" ca-XV \
Catalan ca \
"Chinese (simplified)" zh-CN \
"Chinese (traditional)" zh-TW \
Croatian hr \
Czech cs \
Danish da \
Dogri dgo \
Dutch nl \
Dzongkha dz \
Esperanto eo \
Estonian et \
Finnish fi \
French fr \
Galician gl \
Georgian ka \
German de \
Greek el \
Gujarati gu \
Hebrew he \
Hindi hi \
Hungarian hu \
Icelandic is \
Irish ga \
Italian it \
Japanese ja \
Kannada kn \
Kashmiri ks \
Kazakh kk \
"Khmer (Cambodia)" km \
Kinyarwanda rw \
Konkani kok \
Korean ko \
Kurdish ku \
Lao lo \
Latvian lv \
Lithuanian lt \
Macedonian mk \
Maithili mai \
Malayalam ml \
Manipuri mni \
Marathi mr \
Mongolian mn \
"Ndebele (South)" nr \
Nepali ne \
"Northern Sotho" nso \
"Norwegian Bokmal" nb \
Norwegian nn \
Occitan oc \
Oriya or \
Oromo om \
Persian fa \
Polish pl \
"Portuguese (Brasil)" pt-BR \
Portuguese pt \
"Punjabi (India)" pa-IN \
Romanian ro \
Russian ru \
"Sanskrit (India)" sa-IN \
Santali sat \
Serbian sr \
Serbo-Croatian sh \
Sindhi sd \
Singhalese si \
Slovak sk \
Slovenian sl \
"Southern Sotho" st \
Spanish es \
"Swahili (Tanzania)" sw-TZ \
Swati ss \
Swedish sv \
Tajik tg \
Tamil ta \
Telugu te \
Thai th \
Tibetan bo \
Tsonga ts \
Tswana tn \
Turkish tr \
Uighur ug \
Ukrainian uk \
Uzbek uz \
Venda ve \
Vietnamese vi \
Welsh cy \
Xhosa xh \
Zulu zu \
`

if [ $? != 0 ]; then
  exit
   else
 yad --window-icon=document-save --image=document-save --title="LibreOffice Installer" \
 --button=No:1 --button=Yes:0 \
 --text="Selected language pack: [$LANG]\n\n\nPacmanXG will do the job.\n\n"
 if [ $? != 0 ]; then
  select_language
  else
   pacmanxg --exec "pacman -S --needed libreoffice-$LANG  libreoffice-{common,base,calc,draw,impress,writer,gnome}"
 fi
fi
}


select_language